version: '2'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=productionpassword
  owncloud:
    volumes:
      - /var/www/owncloud/apps:/var/www/html/apps
      - /var/www/owncloud/config:/var/www/html/config
      - /var/www/owncloud/data:/var/www/html/data
